//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartManufacturingLocal_PLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_Machine
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public int ManualId { get; set; }
        public string ExtraField1 { get; set; }
        public string ExtraField2 { get; set; }
    }
}
