//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartManufacturingLocal_PLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoveableMachineProductionData
    {
        public long Id { get; set; }
        public string ManualId { get; set; }
        public decimal ProductionCount { get; set; }
        public decimal TempProductionCount { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<long> ChildMachineId { get; set; }
        public Nullable<bool> DataSynchronizationStatus { get; set; }
        public string TimeFormatCount { get; set; }
    }
}
