//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartManufacturingLocal_PLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public long Id { get; set; }
        public int MachineManualId { get; set; }
        public long ProductionCount { get; set; }
        public long ProductionCountRaw { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    }
}
